### ISSUE TITLE
Quantum Shield Generator (usually) doesn't work

### ISSUE THREAD

**Issue by MightyW0lf** [Keroro1454/Supply-Drop#10]
Sometimes (most of the time) the excess damage is negated and sometimes it's not. [A video with a brief demonstration.](https://youtu.be/gfPKPDiRTh8)

Mods:
* ThinkInvis-TILER2-3.0.4
* bbepis-BepInExPack-5.3.1
* tristanmcpherson-R2API-2.5.14
* **Keroro1454-Supply_Drop-1.4.1**
* Harb-DebugToolkit-3.4.2

**Comment by Keroro1454** [comment]
Addressed in 1.4.2, thank you very much for the report!
