### ISSUE TITLE
Items disabled in config still appear in the logbook and can be gained via console commands / other mods

### ISSUE THREAD

**Issue by gaforb** [Keroro1454/Supply-Drop#12]
May also be that the items can be given to enemies, though I haven't seen this while playing yet.

**Comment by Keroro1454** [comment]
Unfortunately, this is not an issue with the mod but a result of how TILER2 handles disabling items via config. As of now there are no plans to transition Supply Drop away from TILER2, and I am not aware of any plans by TILER2's developer to fix this issue at the moment. Apologies, but thank you very much for your report!
