### ISSUE TITLE
Quantum Shield Generator OSP effect applying armor after reducing damage

### ISSUE THREAD

**Issue by gaforb** [Keroro1454/Supply-Drop#14]
Title. Tested with only Supply Drop (and Aetherium) installed. Confirmed behavior both with mul-t's base armor and with Shielding Core from Aetherium (as I initially suspected this was the issue)

**Comment by A7MAD8** [comment]
T

**Comment by gaforb** [comment]
Per Discord - solution is to take the damage value after it's been reduced by QSG and multiply it by 1 / (100 / (100+armor) )

**Comment by Keroro1454** [comment]
Fixed with 1.4.4. Thanks for the report!

**Comment by gaforb** [comment]
Still bugged as of 1.4.4 - You can see the effect if you have QSG as Mul-T. Fall damage leaves you with a small amount of shield, but using a blood shrine (which ignores armor) leaves you with none.

**Comment by Keroro1454** [comment]
I believe shield bugs were fixed, please let me know if any issues are persisting.
