### ISSUE TITLE
Vintage Plague Hat doesn't work when entering a new stage

### ISSUE THREAD

**Issue by MightyW0lf** [Keroro1454/Supply-Drop#19]
After entering a new stage, the bonus health from the Vintage Plague Hat doesn't work. It gets fixed after receiving an item or after using an equipment (and maybe other things, these are just the ones that I know about). [Demo video](https://youtu.be/-vCqz-p9Tgk), [log output](https://pastebin.com/0QE0eWFR).

Mods installed:
* ThinkInvis-TILER2-3.0.4
* bbepis-BepInExPack-5.3.1
* tristanmcpherson-R2API-2.5.14
* **Keroro1454-Supply_Drop-1.4.5**
* Harb-DebugToolkit-3.4.2

**Comment by Keroro1454** [comment]
I believe this is functional now, please let me know if the issue is persisting.
