### ISSUE TITLE
Coming back

### ISSUE THREAD

**Issue by Unknownusername0001** [Keroro1454/Supply-Drop#21]
Are you going to update this to work with the latest version of risk of rain 2?

**Comment by Keroro1454** [comment]
Hi, I intend to update the mod in a few weeks. I don't have the time right now to dedicate to learning all the changes that need to be made to ensure compatibility. Sorry for the wait!

**Comment by Unknownusername0001** [comment]
Okay thank you i just wanted to know because me and my friends really liked your mod and cant wait till you update it :)
