### ISSUE TITLE
Cannot initialize properly after the latest TILER update

### ISSUE THREAD

**Issue by wyykak** [Keroro1454/Supply-Drop#22]
[Info   :   BepInEx] Loading [Supply Drop 1.4.6]
[Error  : Unity Log] TypeLoadException: Could not resolve type with token 0100002e (from typeref, class/assembly TILER2.StatHooks, TILER2, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null)
Stack trace:
TILER2.T2Module.SetupAll_PluginStart (System.Collections.Generic.IEnumerable`1[T] modulesToSetup, System.Boolean installUnmanaged) (at <7fc2f473a9c84ed79fa175910cc116e5>:IL_0051)
K1454.SupplyDrop.SupplyDropPlugin.Awake () (at <24337f3f0ce04cc7a0be167de40055b1>:IL_00DE)
UnityEngine.GameObject:AddComponent(Type)
BepInEx.Bootstrap.Chainloader:Start()
UnityEngine.Application:.cctor()
RoR2.Console:RegisterLogHandler()

**Comment by Keroro1454** [comment]
Fixed as of TILER compatibility patch, thank you for the report!
