### ISSUE TITLE
[Suggestion] A small feature request

### ISSUE THREAD

**Issue by HR-UP** [Keroro1454/Supply-Drop#25]
Hi.
Is there a way to add a hotkey, pressing which you would cripple yourself by [your current shield value] pts. of damage to make use of the Unassuming Tie move speed buff?

**Comment by Keroro1454** [comment]
Working on the mod again.

No plans to add this at the moment, utilize fall damage or other sources of self-damage like Hellfire Tincture. Just having a button makes it feel like a bootleg Gorag's to me.

Thanks for the thoughts anyway!
