### ISSUE TITLE
Plauge Hat locking clients in drop pod

### ISSUE THREAD

**Issue by Kalkune** [Keroro1454/Supply-Drop#26]
The log size is way to big. Here's the stack trace for it.

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
SupplyDrop.Items.PlagueHat.GetTotalUtilityItems (On.RoR2.CharacterBody+orig_OnInventoryChanged orig, RoR2.CharacterBody self) (at <ea26628d56e84b3eb1a0138c4199e432>:IL_0030)
DMD<>?1554557696.Hook<RoR2.CharacterBody::OnInventoryChanged>?-897300608 (RoR2.CharacterBody ) (at <b81e91a93f374aa4949ac421b28c3f0d>:IL_0014)
DMD<>?1554557696.Trampoline<RoR2.CharacterBody::OnInventoryChanged>?-697036800 (RoR2.CharacterBody ) (at <027cb2d5dbc24dce996478f44f7d04b8>:IL_0020)
SupplyDrop.Items.PlagueMask.GetTotalDamageItems (On.RoR2.CharacterBody+orig_OnInventoryChanged orig, RoR2.CharacterBody self) (at <ea26628d56e84b3eb1a0138c4199e432>:IL_0001)
DMD<>?1554557696.Hook<RoR2.CharacterBody::OnInventoryChanged>?-138489472 (RoR2.CharacterBody ) (at <b5fe11f695b2465690fe6ac24193aa35>:IL_0014)
DMD<>?1554557696.Trampoline<RoR2.CharacterBody::OnInventoryChanged>?-2021462016 (RoR2.CharacterBody ) (at <10d5021bf0844653b0b9a8b68b869ed5>:IL_0020)
Starstorm2.Cores.Items.DormantFungus.CharacterBody_OnInventoryChanged (On.RoR2.CharacterBody+orig_OnInventoryChanged orig, RoR2.CharacterBody self) (at <aaa7a061789647cf8a7ecc07ebf19200>:IL_002B)
DMD<>?1554557696.Hook<RoR2.CharacterBody::OnInventoryChanged>?-1840834176 (RoR2.CharacterBody ) (at <fbea8b9daa1648ebb386bc9dbe5050f9>:IL_0014)
DMD<>?1554557696.Trampoline<RoR2.CharacterBody::OnInventoryChanged>?-1385533440 (RoR2.CharacterBody ) (at <6690771384874c0c9f3892341e4749fe>:IL_0020)
Starstorm2.Cores.Items.Diary.CharacterBody_OnInventoryChanged (On.RoR2.CharacterBody+orig_OnInventoryChanged orig, RoR2.CharacterBody self) (at <aaa7a061789647cf8a7ecc07ebf19200>:IL_000F)
DMD<>?1554557696.Hook<RoR2.CharacterBody::OnInventoryChanged>?315232000 (RoR2.CharacterBody ) (at <c11f394991104d688a94ad11aa6db68b>:IL_0014)
DMD<>?1554557696.Trampoline<RoR2.CharacterBody::OnInventoryChanged>?-275318784 (RoR2.CharacterBody ) (at <cb565ee98be8400ca9f8b0c5382c7a15>:IL_0020)
Starstorm2.Cores.Items.WatchMetronome.CharacterBody_OnInventoryChanged (On.RoR2.CharacterBody+orig_OnInventoryChanged orig, RoR2.CharacterBody self) (at <aaa7a061789647cf8a7ecc07ebf19200>:IL_0029)
DMD<>?1554557696.Hook<RoR2.CharacterBody::OnInventoryChanged>?-65204480 (RoR2.CharacterBody ) (at <bf4e028f6c81473bb6a8643058a3ae20>:IL_0014)
DMD<>?1554557696.Trampoline<RoR2.CharacterBody::OnInventoryChanged>?143280128 (RoR2.CharacterBody ) (at <08c72dcd0dc046d085d21d259e380cbc>:IL_0020)
Starstorm2.Cores.Items.HuntersSigil.CharacterBody_OnInventoryChanged (On.RoR2.CharacterBody+orig_OnInventoryChanged orig, RoR2.CharacterBody self) (at <aaa7a061789647cf8a7ecc07ebf19200>:IL_000F)
DMD<>?1554557696.Hook<RoR2.CharacterBody::OnInventoryChanged>?-194096768 (RoR2.CharacterBody ) (at <17072d3ca0864b5297fb444ff2186347>:IL_0014)
DMD<>?1554557696.Trampoline<RoR2.CharacterBody::OnInventoryChanged>?-1908688896 (RoR2.CharacterBody ) (at <edba7587bee4437199d40aefb60d43b3>:IL_0020)
AspectsToItems.AspectsToItems.EliteBuffsOnYellow (On.RoR2.CharacterBody+orig_OnInventoryChanged orig, RoR2.CharacterBody self) (at <e9b9fa15c9e5424ea5b4ac749d100f64>:IL_00B0)
DMD<>?1554557696.Hook<RoR2.CharacterBody::OnInventoryChanged>?285996416 (RoR2.CharacterBody ) (at <7c425ff12ea24e4a8956881f1c164e50>:IL_0014)
DMD<>?1554557696.Trampoline<RoR2.CharacterBody::OnInventoryChanged>?1845947392 (RoR2.CharacterBody ) (at <ddd2faea84c240aaa5217045b31e5282>:IL_0020)
GoldenCoastPlus.GoldenCoastPlus.CharacterBody_OnInventoryChanged (On.RoR2.CharacterBody+orig_OnInventoryChanged orig, RoR2.CharacterBody self) (at <6dee3e4d01e1472ba7506054674a9258>:IL_0001)
DMD<>?1554557696.Hook<RoR2.CharacterBody::OnInventoryChanged>?-1072581888 (RoR2.CharacterBody ) (at <921f65bfb1a54c1ca757c54c839a195e>:IL_0014)
DMD<>?1554557696.Trampoline<RoR2.CharacterBody::OnInventoryChanged>?1296037888 (RoR2.CharacterBody ) (at <3d7180122c7c4d6baa2051da6aa27298>:IL_0020)
MeltingPot.Items.BurningSoul.HandleBurningCtrl (On.RoR2.CharacterBody+orig_OnInventoryChanged orig, RoR2.CharacterBody self) (at <966cd46a5cdc4f1eb136a75b32a46de0>:IL_000F)
DMD<>?1554557696.Hook<RoR2.CharacterBody::OnInventoryChanged>?1199560448 (RoR2.CharacterBody ) (at <0ca9e6a6b5b5462dae7be98e18f8426c>:IL_0014)
DMD<>?1554557696.Trampoline<RoR2.CharacterBody::OnInventoryChanged>?-1382506496 (RoR2.CharacterBody ) (at <631abbf1158842598acf154d5ae6a17e>:IL_0020)
MeltingPot.Items.EchoBang.HandleEchoCtrl (On.RoR2.CharacterBody+orig_OnInventoryChanged orig, RoR2.CharacterBody self) (at <966cd46a5cdc4f1eb136a75b32a46de0>:IL_000F)
DMD<>?1554557696.Hook<RoR2.CharacterBody::OnInventoryChanged>?104976768 (RoR2.CharacterBody ) (at <2b5e4d3e64464a6c928773b1098e978f>:IL_0014)
DMD<>?1554557696.Trampoline<RoR2.CharacterBody::OnInventoryChanged>?-1728435200 (RoR2.CharacterBody ) (at <deeb5b262aba430ca00053bdbeaef080>:IL_0020)
MeltingPot.Items.ReactiveArmour.HandleArmourCtrl (On.RoR2.CharacterBody+orig_OnInventoryChanged orig, RoR2.CharacterBody self) (at <966cd46a5cdc4f1eb136a75b32a46de0>:IL_000F)
DMD<>?1554557696.Hook<RoR2.CharacterBody::OnInventoryChanged>?-1276253440 (RoR2.CharacterBody ) (at <46a24bc202b348a08f31e2fb6bb72e87>:IL_0014)
DMD<>?1554557696.Trampoline<RoR2.CharacterBody::OnInventoryChanged>?1147936768 (RoR2.CharacterBody ) (at <d1137c8f459e4bb0881db6caa36cea1a>:IL_0020)
EliteAspectsChanges.EliteAspectsChanges.ImmediateHauntedWardUpdate (On.RoR2.CharacterBody+orig_OnInventoryChanged orig, RoR2.CharacterBody self) (at <cb001f5b5430450cb0091e99940a6b6d>:IL_0001)
DMD<>?1554557696.Hook<RoR2.CharacterBody::OnInventoryChanged>?-2072548608 (RoR2.CharacterBody ) (at <de07d40755a84a08a4984adc2e5819b3>:IL_0014)
DMD<>?1554557696.Trampoline<RoR2.CharacterBody::OnInventoryChanged>?157066240 (RoR2.CharacterBody ) (at <3f166fe0692c48308509128715d6dcde>:IL_0020)
SillyGlasses.SillyGlassesPlugin.InvChangedHook (On.RoR2.CharacterBody+orig_OnInventoryChanged orig, RoR2.CharacterBody self) (at <2a4b893799c24e75b365f2980ca73719>:IL_0099)
DMD<>?1554557696.Hook<RoR2.CharacterBody::OnInventoryChanged>?1031658496 (RoR2.CharacterBody ) (at <e1a68a78ad5a43999832b60dcf71076c>:IL_0014)
DMD<>?1554557696.Trampoline<RoR2.CharacterBody::OnInventoryChanged>?270936064 (RoR2.CharacterBody ) (at <f4d3371dada94ba2b064653a894cc3aa>:IL_0020)
TPDespair.ZetAspects.EffectHooks+<>c.<ApplyAspectBuffOnInventoryChangedHook>b__39_0 (On.RoR2.CharacterBody+orig_OnInventoryChanged orig, RoR2.CharacterBody self) (at <ebd43324101342ffbcd4c5d94428c7f4>:IL_0037)
DMD<>?1554557696.Hook<RoR2.CharacterBody::OnInventoryChanged>?-1217176576 (RoR2.CharacterBody ) (at <14d0af755f6a45fb88af810d1b56db13>:IL_0014)
DMD<>?1554557696.Trampoline<RoR2.CharacterBody::OnInventoryChanged>?1504837632 (RoR2.CharacterBody ) (at <3f0b6dd57ec845d5a83d78dd13f24aae>:IL_0020)
SpaceSpinach.Hooks+<>c.<Init>b__0_2 (On.RoR2.CharacterBody+orig_OnInventoryChanged orig, RoR2.CharacterBody self) (at <ba11482b416047eb9a187b2d07ac68e5>:IL_0179)
DMD<>?1554557696.Hook<RoR2.CharacterBody::OnInventoryChanged>?1900729984 (RoR2.CharacterBody ) (at <adcdb1f662144400abcbecb39295e4e6>:IL_0014)
DMD<>?1554557696.Trampoline<RoR2.CharacterBody::OnInventoryChanged>?2028002304 (RoR2.CharacterBody ) (at <73eb9efb2ed842e18bb1cadd0f92f8a5>:IL_0020)
ThinkInvisible.ClassicItems.LifeSavings.On_CBOnInventoryChanged (On.RoR2.CharacterBody+orig_OnInventoryChanged orig, RoR2.CharacterBody self) (at <f12240b757ee4df5a23e3fa25869943f>:IL_0000)
DMD<>?1554557696.Hook<RoR2.CharacterBody::OnInventoryChanged>?699802496 (RoR2.CharacterBody ) (at <f7a276da10c1479a960f25ee16045f08>:IL_0014)
DMD<>?1554557696.Trampoline<RoR2.CharacterBody::OnInventoryChanged>?277018624 (RoR2.CharacterBody ) (at <d8cc05d005d84e66bc7b5e536b59c334>:IL_0020)
ThinkInvisible.ClassicItems.GoldenGun.On_CBInventoryChanged (On.RoR2.CharacterBody+orig_OnInventoryChanged orig, RoR2.CharacterBody self) (at <f12240b757ee4df5a23e3fa25869943f>:IL_0000)
DMD<>?1554557696.Hook<RoR2.CharacterBody::OnInventoryChanged>?708887168 (RoR2.CharacterBody ) (at <d97835372db142c689f69414942f7f6f>:IL_0014)
DMD<>?1554557696.Trampoline<RoR2.CharacterBody::OnInventoryChanged>?-1219990528 (RoR2.CharacterBody ) (at <f4dbcc4f61724c23806bce689f15d4a1>:IL_0020)
ThinkInvisible.ClassicItems.Imprint.On_CBInventoryChanged (On.RoR2.CharacterBody+orig_OnInventoryChanged orig, RoR2.CharacterBody self) (at <f12240b757ee4df5a23e3fa25869943f>:IL_0000)
DMD<>?1554557696.Hook<RoR2.CharacterBody::OnInventoryChanged>?-1504983168 (RoR2.CharacterBody ) (at <d2b8f20336ee45859e267991918262bc>:IL_0014)
DMD<>?1554557696.Trampoline<RoR2.CharacterBody::OnInventoryChanged>?1149753344 (RoR2.CharacterBody ) (at <d427c5e2006a42abac65e079d1a2992a>:IL_0020)
ThinkInvisible.ClassicItems.PhotonJetpack.On_CBInventoryChanged (On.RoR2.CharacterBody+orig_OnInventoryChanged orig, RoR2.CharacterBody self) (at <f12240b757ee4df5a23e3fa25869943f>:IL_0000)
DMD<>?1554557696.Hook<RoR2.CharacterBody::OnInventoryChanged>?2106503808 (RoR2.CharacterBody ) (at <1fdcfd0a5b174d38868b8132295e7556>:IL_0014)
DMD<>?1554557696.Trampoline<RoR2.CharacterBody::OnInventoryChanged>?-926905344 (RoR2.CharacterBody ) (at <820df0aeeeb84748a6aea90f5acb52d0>:IL_0020)
ThinkInvisible.ClassicItems.Scepter.On_CBOnInventoryChanged (On.RoR2.CharacterBody+orig_OnInventoryChanged orig, RoR2.CharacterBody self) (at <f12240b757ee4df5a23e3fa25869943f>:IL_0000)
DMD<>?1554557696.Hook<RoR2.CharacterBody::OnInventoryChanged>?917155200 (RoR2.CharacterBody ) (at <214896f6e8eb4423a55a0af29aaf6fde>:IL_0014)
DMD<>?1554557696.Trampoline<RoR2.CharacterBody::OnInventoryChanged>?-348468224 (RoR2.CharacterBody ) (at <4861f455fa5e497ab3ed3c2cf6096d31>:IL_0020)
MysticsItems.Items.CoffeeBoostOnItemPickup.<OnLoad>b__2_3 (On.RoR2.CharacterBody+orig_OnInventoryChanged orig, RoR2.CharacterBody self) (at <e62d18edfd084fbfae7bf9e6638bce50>:IL_0001)
DMD<>?1554557696.Hook<RoR2.CharacterBody::OnInventoryChanged>?-1346076800 (RoR2.CharacterBody ) (at <c699249df85b47c6954751080c66f82e>:IL_0014)
DMD<>?1554557696.Trampoline<RoR2.CharacterBody::OnInventoryChanged>?-2003703808 (RoR2.CharacterBody ) (at <491fe6a9f1c24e0c98e4f79f531f7ba4>:IL_0020)
MysticsItems.Items.ExtraShrineUse+<>c.<OnLoad>b__1_0 (On.RoR2.CharacterBody+orig_OnInventoryChanged orig, RoR2.CharacterBody self) (at <e62d18edfd084fbfae7bf9e6638bce50>:IL_0001)
DMD<>?1554557696.Hook<RoR2.CharacterBody::OnInventoryChanged>?1761536896 (RoR2.CharacterBody ) (at <5d718185750e40169ea45ddb847805f2>:IL_0014)
RoR2.Inventory.OnDeserialize (UnityEngine.Networking.NetworkReader reader, System.Boolean initialState) (at <da7c19fa62814b28bdb8f3a9223868e1>:IL_00D2)
UnityEngine.Networking.NetworkIdentity.OnUpdateVars (UnityEngine.Networking.NetworkReader reader, System.Boolean initialState) (at <73dce905efe04cb5acf013e51496d921>:IL_001B)
UnityEngine.Networking.ClientScene.OnUpdateVarsMessage (UnityEngine.Networking.NetworkMessage netMsg) (at <73dce905efe04cb5acf013e51496d921>:IL_0059)
UnityEngine.Networking.NetworkConnection.HandleReader (UnityEngine.Networking.NetworkReader reader, System.Int32 receivedSize, System.Int32 channelId) (at <73dce905efe04cb5acf013e51496d921>:IL_010B)
UnityEngine.Networking.NetworkConnection.HandleBytes (System.Byte[] buffer, System.Int32 receivedSize, System.Int32 channelId) (at <73dce905efe04cb5acf013e51496d921>:IL_0007)
UnityEngine.Networking.NetworkConnection.TransportReceive (System.Byte[] bytes, System.Int32 numBytes, System.Int32 channelId) (at <73dce905efe04cb5acf013e51496d921>:IL_0000)
UnityEngine.Networking.NetworkClient.Update () (at <73dce905efe04cb5acf013e51496d921>:IL_017F)
UnityEngine.Networking.NetworkClient.UpdateClients () (at <73dce905efe04cb5acf013e51496d921>:IL_001C)
UnityEngine.Networking.NetworkIdentity.UNetStaticUpdate () (at <73dce905efe04cb5acf013e51496d921>:IL_0005)

**Comment by Keroro1454** [comment]
Finally working on this mod again. This will be fixed in the upcoming patch.

Thanks for the report!
