### ISSUE TITLE
Make item visuals compatible with modded survivors.

### ISSUE THREAD

**Issue by 4AC11** [Keroro1454/Supply-Drop#28]
Items from this mod appear massive on modded survivors. I originally reported this to the Deputy mod page (https://github.com/BogRtM/Deputy/issues/12#issue-1977450365) because I thought it was only on her, but after playing some other modded survivors it also happens on Nemesis Commando, Assassin, among others. I haven't tested every modded character in existence, but I think I can infer that this is an issue on most of them.
Although this is just a visual thing, it can impede visibility, especially when it covers the entire character model.

**Comment by Keroro1454** [comment]
Although item displays have not been added for all modded survivors, items displaying incorrectly has been fixed as of 1.4.11.
