### ISSUE TITLE
Shell Plating ignores Configuration settings

### ISSUE THREAD

**Issue by AndyDoe** [Keroro1454/Supply-Drop#9]
When using the .cfg to alter the maximum Armor obtained from Shell Plating, it ignores the settings in the config and still caps at 10.
![shellplate](https://user-images.githubusercontent.com/77365810/104388134-6dbcbc80-54ed-11eb-899e-a5385687c8f6.png)
![shellplate2](https://user-images.githubusercontent.com/77365810/104388156-7b724200-54ed-11eb-8429-6aa095af4fec.png)
![shellplate3](https://user-images.githubusercontent.com/77365810/104388224-a492d280-54ed-11eb-8b3f-c0b3235fd971.png)
The ShellStacksMax buff appears starting at the maximum value specified in the .cfg, but armor will continue to be gained until it reaches the default maximum of 10.

![shellplate4](https://user-images.githubusercontent.com/77365810/104388317-ce4bf980-54ed-11eb-9f1d-d09a0be333ea.png)
Additionally, when Shell Plating is lost or removed, the ShellStacksMax buff persists despite the armor being lost.

**Comment by Keroro1454** [comment]
Addressed in 1.4.2, config variables hadn't been fully transitioned into the actual code. Thank you very much for the report!

**Comment by AndyDoe** [comment]
Thanks for the timely fix! Unrelated, but is there any chance for items disabled in the config not to appear in the Logbook in a future update?
